#!/usr/bin/env node
// assets/sources.json -> assets/manifest.json: every declared asset measured from its file (width, height,
// bytes, sha256). Authoring tool; the manifest is committed and the test recomputes it.
import { createHash } from 'node:crypto'
import { readFileSync, writeFileSync } from 'node:fs'
import sharp from 'sharp'

const sources = JSON.parse(readFileSync('assets/sources.json', 'utf8'))
const assets = []
for (const group of sources.groups) {
  for (const item of group.items) {
    const file = `public${item.path}`
    const bytes = readFileSync(file)
    const meta = await sharp(bytes).metadata()
    assets.push({
      id: item.id,
      path: item.path,
      alt: item.alt,
      kind: group.kind,
      width: meta.width,
      height: meta.height,
      format: meta.format,
      bytes: bytes.length,
      sha256: createHash('sha256').update(bytes).digest('hex'),
      source: group.source,
    })
  }
}
const ids = new Set()
for (const a of assets) { if (ids.has(a.id)) throw new Error(`asset id declared twice: ${a.id}`); ids.add(a.id) }
writeFileSync('assets/manifest.json', JSON.stringify({ note: 'GENERATED by scripts/measure-assets.mjs from assets/sources.json - edit the sources, then regenerate. Every page asset resolves by id here (S1); renditions are derived from the master at request time (next/image), never served as the master.', assets }, null, 2) + '\n')
console.log(`manifest: ${assets.length} assets, ${assets.filter((a) => a.kind === 'proof').length} proof photographs, ${assets.filter((a) => a.kind === 'swatch').length} swatches, ${assets.filter((a) => a.kind === 'metal').length} metals, ${assets.filter((a) => a.kind === 'brand').length} brand`)
